// Plaats een gebouw op het bord.

const config = require("../other/config.js");
const profileModel = require("../models/profileSchema");
const editJsonFile = require("edit-json-file");

module.exports = {
    name: "tradingplace",
    aliases: config.aliases.aliasestradingplace,
    cooldown: config.cooldown.cooldowntradingplace,
    permissions: config.permissions.permissiontradingplace,
    description: "Place an owned building on your board.",
    async execute(message, args, cmd, client, Discord, profileData) {
        try {
            const buildinglist = [
                "housetier1",
                "housetier2",
                "housetier3",
                "housetier4",
                "housetier5",
                "river",
                "forest",
                "beach",
                "mine",
                "field",
                "oilwell",
                "park",
                "school",
                "cinema",
                "restaurant",
                "hotel",
                "warehousetier1",
                "warehousetier2",
                "warehousetier3",
                "warehousetier4",
                "warehousetier5",
                "policetier1",
                "policetier2",
                "policetier3",
                "firedepartmenttier1",
                "firedepartmenttier2",
                "firedepartmenttier3",
                "hospitaltier1",
                "hospitaltier2",
                "hospitaltier3",
                "malltier1",
                "malltier2",
                "cityhalltier1",
                "cityhalltier2",
                "landfilltier1",
                "landfilltier2",
                "landfilltier3",
                "nuclearreactortier1",
                "nuclearreactortier2",
                "windmill",
                "sonarpanel",
                "sawmilltier1",
                "sawmilltier2",
                "refinerytier1",
                "refinerytier2",
                "interiorshoptier1",
                "interiorshoptier2",
                "clothingshoptier1",
                "clothingshoptier2",
                "drugstoretier1",
                "drugstoretier2",
                "conveniencestoretier1",
                "conveniencestoretier2",
                "conveniencestoretier3",
                "devicestoretier1",
                "devicestoretier2",
                "devicestoretier3",
                "reactortier1",
                "reactortier2",
                "factorytier1",
                "factorytier2",
                "energyplanttier1",
                "energyplanttier2",
                "energyplanttier3",
                "waterplanttier1",
                "waterplanttier2",
                "waterplanttier3",
                "gasplanttier1",
                "gasplanttier2",
                "gasplanttier3",
            ]
            const placelist = [
                "a1",
                "a2",
                "a3",
                "a4",
                "a5",
                "a6",
                "a7",
                "a8",
                "a9",
                "a10",
                "a11",
                "a12",
                "a13",
                "a14",
                "a15",
                "b1",
                "b2",
                "b3",
                "b4",
                "b5",
                "b6",
                "b7",
                "b8",
                "b9",
                "b10",
                "b11",
                "b12",
                "b13",
                "b14",
                "b15",
                "c1",
                "c2",
                "c3",
                "c4",
                "c5",
                "c6",
                "c7",
                "c8",
                "c9",
                "c10",
                "c11",
                "c12",
                "c13",
                "c14",
                "c15",
                "d1",
                "d2",
                "d3",
                "d4",
                "d5",
                "d6",
                "d7",
                "d8",
                "d9",
                "d10",
                "d11",
                "d12",
                "d13",
                "d14",
                "d15",
                "e1",
                "e2",
                "e3",
                "e4",
                "e5",
                "e6",
                "e7",
                "e8",
                "e9",
                "e10",
                "e11",
                "e12",
                "e13",
                "e14",
                "e15",
                "f1",
                "f2",
                "f3",
                "f4",
                "f5",
                "f6",
                "f7",
                "f8",
                "f9",
                "f10",
                "f11",
                "f12",
                "f13",
                "f14",
                "f15",
                "g1",
                "g2",
                "g3",
                "g4",
                "g5",
                "g6",
                "g7",
                "g8",
                "g9",
                "g10",
                "g11",
                "g12",
                "g13",
                "g14",
                "g15",
                "h1",
                "h2",
                "h3",
                "h4",
                "h5",
                "h6",
                "h7",
                "h8",
                "h9",
                "h10",
                "h11",
                "h12",
                "h13",
                "h14",
                "h15",
                "i1",
                "i2",
                "i3",
                "i4",
                "i5",
                "i6",
                "i7",
                "i8",
                "i9",
                "i10",
                "i11",
                "i12",
                "i13",
                "i14",
                "i15",
                "j1",
                "j2",
                "j3",
                "j4",
                "j5",
                "j6",
                "j7",
                "j8",
                "j9",
                "j10",
                "j11",
                "j12",
                "j13",
                "j14",
                "j15",
                "k1",
                "k2",
                "k3",
                "k4",
                "k5",
                "k6",
                "k7",
                "k8",
                "k9",
                "k10",
                "k11",
                "k12",
                "k13",
                "k14",
                "k15",
                "l1",
                "l2",
                "l3",
                "l4",
                "l5",
                "l6",
                "l7",
                "l8",
                "l9",
                "l10",
                "l11",
                "l12",
                "l13",
                "l14",
                "l15",
                "m1",
                "m2",
                "m3",
                "m4",
                "m5",
                "m6",
                "m7",
                "m8",
                "m9",
                "m10",
                "m11",
                "m12",
                "m13",
                "m14",
                "m15",
                "n1",
                "n2",
                "n3",
                "n4",
                "n5",
                "n6",
                "n7",
                "n8",
                "n9",
                "n10",
                "n11",
                "n12",
                "n13",
                "n14",
                "n15",
                "o1",
                "o2",
                "o3",
                "o4",
                "o5",
                "o6",
                "o7",
                "o8",
                "o9",
                "o10",
                "o11",
                "o12",
                "o13",
                "o14",
                "o15"
            ]
            const building1 = args[0]
            const place1 = args[1]
            const building = building1.toLowerCase();
            const place = place1.toLowerCase();
            if (!building) {
                return message.channel.send(`What building type would you like to place?`)
            }
            if (!place) {
                return message.channel.send(`Where would you like to place this?`)
            }
            if (buildinglist.includes(building) == false) {
                return message.channel.send(`The building that you are trying to place doesn't exist or you have a typo.`)
            }
            ;
            if (placelist.includes(place) == false) {
                return message.channel.send(`The place that you are trying to build on doesn't exist or you have a typo.`)
            }
            ;
            try {
                if (1 > profileData[building]) {
                    return message.channel.send(`You don't have any buildings of this type left.`)
                }
                const amountleft = profileData[building] - 1
                await profileModel.findOneAndUpdate(
                    {
                        userID: message.author.id,
                    },
                    {
                        $inc: {
                            [building]: -1,
                            actions: 1,
                            timesbuilt: 1,
                        },
                        $set: {
                            [place]: building,
                        },
                    },
                );
                message.channel.send(`You have succesfully placed \`${building}\` on \`${place}\`. You have \`${amountleft}\` \`${building}\` left.`)
            } catch (err) {
                console.log(err);
                message.channel.send(`Error executing command. EC: \`${config.errorcodes.err2}\`.`) // Error Systeem
            }
        } catch (err) {
            console.log(err)
            message.channel.send(`Error executing command. EC: \`${config.errorcodes.err2}\`.`) // Error Systeem
        }
    },
};
