// Maak een profiel aan als iemand de server joined.

const profileModel = require("../../models/profileSchema");
const config = require("./../../Other/config.js");

module.exports = async (message, args, cmd, client, Discord, member, profileData) => {
  const tagfull = message.author.tag
  const tag = tagfull.substr(-4);
  const rndIntmax = 10000000000000
  const rndIntmin = 1
  const rndInt = Math.round(Math.floor(Math.random() * rndIntmax) + rndIntmin)
  let profile = await profileModel.create({
    userID: message.author.id,
    name: message.author.username,
    avatar: message.author.avatar,
    bot: message.author.bot,
    tag: tag,
    uni: rndInt,
    warnings: 0,

    scrapexotic: 0,
    scraplegendary: 0,
    scrapepic: 0,
    scraprare: 0,
    scrapuncommon: 0,
    scrapcommon: 0,

    music1: "https://www.youtube.com/",
    music2: "https://www.youtube.com/",
    music3: "https://www.youtube.com/",
    music4: "https://www.youtube.com/",
    music5: "https://www.youtube.com/",
    music6: "https://www.youtube.com/",

    level: 0,
    experience: 0,

    wallet: 0,
    bank: 0,

    boxesultra: 0,
    boxessuper: 0,
    boxesnormal: 0,

    shardsdiamond: 0,
    shardsplatinum: 0,
    shardsgold: 0,
    shardssilver: 0,
    shardsbronze: 0,
    shardsiron: 0,

    xi: 0,
    pi: 0,

    tradesaccepted: 0,
    tradescancelled: 0,
    actions: 0,
    amountbought: 0,
    amountsold: 0,

    steel: 0,
    steelpart: 0,
    iron: 0,
    carbon: 0,
    rawiron: 0,

    brick: 0,
    clay: 0,

    woodplank: 0,
    woodpart: 0,
    wood: 0,
    logs: 0,

    pipe: 0,
    plasticpart: 0,
    plastic: 0,

    glass: 0,
    limestone: 0,
    sand: 0,

    granite: 0,
    marble: 0,
    quartz: 0,
    chalk: 0,
    slate: 0,
    basalt: 0,

    phenolicfoam: 0,
    polyurethane: 0,
    xps: 0,
    rockwool: 0,
    foamglass: 0,
    glasswool: 0,
    doubleglass: 0,
    tripleglass: 0,

    fabric: 0,
    cotton: 0,
    fibre: 0,

    bread: 0,
    wheat: 0,
    flower: 0,

    meat: 0,
    animal: 0,

    vegetable: 0,
    plant: 0,

    polymaterial: 0,
    acid: 0,
    catalyst: 0,

    chromepart: 0,
    chrome: 0,
    brasspart: 0,
    brass: 0,

    diamond: 0,
    gold: 0,
    platinum: 0,
    silver: 0,
    copper: 0,
    lithium: 0,
    cobalt: 0,

    componentelectric: 0,
    componentinterior: 0,
    componentclothing: 0,
    componentstarting: 0,

    housetier1: 0,
    housetier2: 0,
    housetier3: 0,
    housetier4: 0,
    housetier5: 0,

    warehousetier: 0,
    policetier: 0,
    firedepartmenttier: 0,
    hospitaltier: 0,
    malltier: 0,
    cityhalltier: 0,
    infrastructuretier: 0,
    landfilltier: 0,

    interiorshoptier: 0,
    clothingshoptier: 0,
    drugstoretier: 0,
    conveniencestoretier: 0,
    devicestoretier: 0,

    happinesspercentage: 0,
    crimerate: 0,
    population: 0,

    reactortier: 0,
    factorytier: 0,
    energyplanttier: 0,
    waterplanttier: 0,
    gasplanttier: 0,

    a1: "Empty",
    a2: "Empty",
    a3: "Empty",
    a4: "Empty",
    a5: "Empty",
    a6: "Empty",
    a7: "Empty",
    a8: "Empty",
    a9: "Empty",
    a10: "Empty",
    a11: "Empty",
    a12: "Empty",
    a13: "Empty",
    a14: "Empty",
    a15: "Empty",
    b1: "Empty",
    b2: "Empty",
    b3: "Empty",
    b4: "Empty",
    b5: "Empty",
    b6: "Empty",
    b7: "Empty",
    b8: "Empty",
    b9: "Empty",
    b10: "Empty",
    b11: "Empty",
    b12: "Empty",
    b13: "Empty",
    b14: "Empty",
    b15: "Empty",
    c1: "Empty",
    c2: "Empty",
    c3: "Empty",
    c4: "Empty",
    c5: "Empty",
    c6: "Empty",
    c7: "Empty",
    c8: "Empty",
    c9: "Empty",
    c10: "Empty",
    c11: "Empty",
    c12: "Empty",
    c13: "Empty",
    c14: "Empty",
    c15: "Empty",
    d1: "Empty",
    d2: "Empty",
    d3: "Empty",
    d4: "Empty",
    d5: "Empty",
    d6: "Empty",
    d7: "Empty",
    d8: "Empty",
    d9: "Empty",
    d10: "Empty",
    d11: "Empty",
    d12: "Empty",
    d13: "Empty",
    d14: "Empty",
    d15: "Empty",
    e1: "Empty",
    e2: "Empty",
    e3: "Empty",
    e4: "Empty",
    e5: "Empty",
    e6: "Empty",
    e7: "Empty",
    e8: "Empty",
    e9: "Empty",
    e10: "Empty",
    e11: "Empty",
    e12: "Empty",
    e13: "Empty",
    e14: "Empty",
    e15: "Empty",
    f1: "Empty",
    f2: "Empty",
    f3: "Empty",
    f4: "Empty",
    f5: "Empty",
    f6: "Empty",
    f7: "Empty",
    f8: "Empty",
    f9: "Empty",
    f10: "Empty",
    f11: "Empty",
    f12: "Empty",
    f13: "Empty",
    f14: "Empty",
    f15: "Empty",
    g1: "Empty",
    g2: "Empty",
    g3: "Empty",
    g4: "Empty",
    g5: "Empty",
    g6: "Empty",
    g7: "Empty",
    g8: "Empty",
    g9: "Empty",
    g10: "Empty",
    g11: "Empty",
    g12: "Empty",
    g13: "Empty",
    g14: "Empty",
    g15: "Empty",
    h1: "Empty",
    h2: "Empty",
    h3: "Empty",
    h4: "Empty",
    h5: "Empty",
    h6: "Empty",
    h7: "Empty",
    h8: "Empty",
    h9: "Empty",
    h10: "Empty",
    h11: "Empty",
    h12: "Empty",
    h13: "Empty",
    h14: "Empty",
    h15: "Empty",
    i1: "Empty",
    i2: "Empty",
    i3: "Empty",
    i4: "Empty",
    i5: "Empty",
    i6: "Empty",
    i7: "Empty",
    i8: "Empty",
    i9: "Empty",
    i10: "Empty",
    i11: "Empty",
    i12: "Empty",
    i13: "Empty",
    i14: "Empty",
    i15: "Empty",
    j1: "Empty",
    j2: "Empty",
    j3: "Empty",
    j4: "Empty",
    j5: "Empty",
    j6: "Empty",
    j7: "Empty",
    j8: "Empty",
    j9: "Empty",
    j10: "Empty",
    j11: "Empty",
    j12: "Empty",
    j13: "Empty",
    j14: "Empty",
    j15: "Empty",
    k1: "Empty",
    k2: "Empty",
    k3: "Empty",
    k4: "Empty",
    k5: "Empty",
    k6: "Empty",
    k7: "Empty",
    k8: "Empty",
    k9: "Empty",
    k10: "Empty",
    k11: "Empty",
    k12: "Empty",
    k13: "Empty",
    k14: "Empty",
    k15: "Empty",
    l1: "Empty",
    l2: "Empty",
    l3: "Empty",
    l4: "Empty",
    l5: "Empty",
    l6: "Empty",
    l7: "Empty",
    l8: "Empty",
    l9: "Empty",
    l10: "Empty",
    l11: "Empty",
    l12: "Empty",
    l13: "Empty",
    l14: "Empty",
    l15: "Empty",
    m1: "Empty",
    m2: "Empty",
    m3: "Empty",
    m4: "Empty",
    m5: "Empty",
    m6: "Empty",
    m7: "Empty",
    m8: "Empty",
    m9: "Empty",
    m10: "Empty",
    m11: "Empty",
    m12: "Empty",
    m13: "Empty",
    m14: "Empty",
    m15: "Empty",
    n1: "Empty",
    n2: "Empty",
    n3: "Empty",
    n4: "Empty",
    n5: "Empty",
    n6: "Empty",
    n7: "Empty",
    n8: "Empty",
    n9: "Empty",
    n10: "Empty",
    n11: "Empty",
    n12: "Empty",
    n13: "Empty",
    n14: "Empty",
    n15: "Empty",
    o1: "Empty",
    o2: "Empty",
    o3: "Empty",
    o4: "Empty",
    o5: "Empty",
    o6: "Empty",
    o7: "Empty",
    o8: "Empty",
    o9: "Empty",
    o10: "Empty",
    o11: "Empty",
    o12: "Empty",
    o13: "Empty",
    o14: "Empty",
    o15: "Empty",
  });
  profile.save();
};