// Bulk update de hele lijst.

const config = require("../Other/config.js");
const profileModel = require("../models/profileSchema");
const editJsonFile = require("edit-json-file");

module.exports = {
    name: "update",
    aliases: config.aliases.aliasesupdate,
    cooldown: config.cooldown.cooldownupdate,
    permissions: config.permissions.permissionupdate,
    description: "Bulk update data.",
    async execute(message, args, cmd, client, Discord, profileData) {
        message.channel.send(`Received, check console.`)
        let file = editJsonFile(`./marketdynprice.json`); // target file
        const filedata = require('./../marketdynprice.json') // current data

        const steel = 1 * filedata.steel;
        const steelpart = 1 * filedata.steelpart;
        const iron = 1 * filedata.iron;
        const carbon = 1 * filedata.carbon;
        const brick = 1 * filedata.brick;
        const clay = 1 * filedata.clay;
        const soil = 1 * filedata.soil;
        const water = 1 * filedata.water;
        const woodplank = 1 * filedata.woodplank;
        const woodpart = 1 * filedata.woodpart;
        const wood = 1 * filedata.wood;
        const log = 1 * filedata.log;
        const bamboo = 1 * filedata.bamboo;
        const pipe = 1 * filedata.pipe;
        const plasticpart = 1 * filedata.plasticpart;
        const plastic = 1 * filedata.plastic;
        const glass = 1 * filedata.glass;
        const limestone = 1 * filedata.limestone;
        const sand = 1 * filedata.sand;
        const plexiglass = 1 * filedata.plexiglass;
        const granite = 1 * filedata.granite;
        const marble = 1 * filedata.marble;
        const quartz = 1 * filedata.quartz;
        const chalk = 1 * filedata.chalk;
        const slate = 1 * filedata.slate;
        const basalt = 1 * filedata.basalt;
        const oil = 1 * filedata.oil;
        const coal = 1 * filedata.coal;
        const ironore = 1 * filedata.ironore;
        const copperore = 1 * filedata.copperore;
        const goldore = 1 * filedata.goldore;
        const gas = 1 * filedata.gas;
        const ceramic = 1 * filedata.ceramic;
        const cork = 1 * filedata.cork;
        const mesh = 1 * filedata.mesh;
        const rubber = 1 * filedata.rubber;
        const uranium = 1 * filedata.uranium;
        const rice = 1 * filedata.rice;
        const rye = 1 * filedata.rye;
        const oats = 1 * filedata.oats;
        const corn = 1 * filedata.corn;
        const barley = 1 * filedata.barley;
        const cassava = 1 * filedata.cassava;
        const soybean = 1 * filedata.soybean;
        const sorghum = 1 * filedata.sorghum;
        const wheat = 1 * filedata.wheat;
        const resin = 1 * filedata.resin;
        const tape = 1 * filedata.tape;
        const glue = 1 * filedata.glue;
        const paper = 1 * filedata.paper;
        const steelsheet = 1 * filedata.steelsheet;
        const cocoabean = 1 * filedata.cocoabean;
        const coffeebean = 1 * filedata.coffeebean;
        const sugar = 1 * filedata.sugar;
        const salt = 1 * filedata.salt;
        const flower = 1 * filedata.flower;
        const bakingpowder = 1 * filedata.bakingpowder;
        const egg = 1 * filedata.egg;
        const fish = 1 * filedata.fish;
        const meat = 1 * filedata.meat;
        const bread = 1 * filedata.bread;
        const asparagus = 1 * filedata.asparagus;
        const eggplant = 1 * filedata.eggplant;
        const broccoli = 1 * filedata.broccoli;
        const cabbage = 1 * filedata.cabbage;
        const avocado = 1 * filedata.avocado;
        const brusselssprout = 1 * filedata.brusselssprout;
        const carrot = 1 * filedata.carrot;
        const beetroot = 1 * filedata.beetroot;
        const garlic = 1 * filedata.garlic;
        const celery = 1 * filedata.celery;
        const cucumber = 1 * filedata.cucumber;
        const greenbean = 1 * filedata.greenbean;
        const leek = 1 * filedata.leek;
        const lettuce = 1 * filedata.lettuce;
        const mushroom = 1 * filedata.mushroom;
        const onion = 1 * filedata.onion;
        const pea = 1 * filedata.pea;
        const pumpkin = 1 * filedata.pumpkin;
        const radish = 1 * filedata.radish;
        const rhubarb = 1 * filedata.rhubarb;
        const sweetpepper = 1 * filedata.sweetpepper;
        const spinach = 1 * filedata.spinach;
        const tomato = 1 * filedata.tomato;
        const sweetpotato = 1 * filedata.sweetpotato;
        const yam = 1 * filedata.yam;
        const potato = 1 * filedata.potato;
        const acerola = 1 * filedata.acerola;
        const apple = 1 * filedata.apple;
        const apricot = 1 * filedata.apricot;
        const banana = 1 * filedata.banana;
        const blackberry = 1 * filedata.blackberry;
        const blackcurrant = 1 * filedata.blackcurrant;
        const blueberry = 1 * filedata.blueberry;
        const breadfruit = 1 * filedata.breadfruit;
        const cantaloupe = 1 * filedata.cantaloupe;
        const cherry = 1 * filedata.cherry;
        const clementine = 1 * filedata.clementine;
        const coconut = 1 * filedata.coconut;
        const cranberry = 1 * filedata.cranberry;
        const datefruit = 1 * filedata.datefruit;
        const fig = 1 * filedata.fig;
        const gooseberry = 1 * filedata.gooseberry;
        const grapefruit = 1 * filedata.grapefruit;
        const grape = 1 * filedata.grape;
        const guava = 1 * filedata.guava;
        const honeydewmelon = 1 * filedata.honeydewmelon;
        const jackfruit = 1 * filedata.jackfruit;
        const jujubefruit = 1 * filedata.jujubefruit;
        const kiwifruit = 1 * filedata.kiwifruit;
        const kumquat = 1 * filedata.kumquat;
        const lemon = 1 * filedata.lemon;
        const lime = 1 * filedata.lime;
        const lychee = 1 * filedata.lychee;
        const mandarin = 1 * filedata.mandarin;
        const mango = 1 * filedata.mango;
        const mulberry = 1 * filedata.mulberry;
        const olive = 1 * filedata.olive;
        const orange = 1 * filedata.orange;
        const papaya = 1 * filedata.papaya;
        const passionfruit = 1 * filedata.passionfruit;
        const peach = 1 * filedata.peach;
        const pear = 1 * filedata.pear;
        const dragonfruit = 1 * filedata.dragonfruit;
        const pineapple = 1 * filedata.pineapple;
        const plum = 1 * filedata.plum;
        const pomegranate = 1 * filedata.pomegranate;
        const prune = 1 * filedata.prune;
        const raspberry = 1 * filedata.raspberry;
        const strawberry = 1 * filedata.strawberry;
        const tangerine = 1 * filedata.tangerine;
        const watermelon = 1 * filedata.watermelon;
        const blackbean = 1 * filedata.blackbean;
        const blackeyedpea = 1 * filedata.blackeyedpea;
        const cannellinibean = 1 * filedata.cannellinibean;
        const chickpea = 1 * filedata.chickpea;
        const greatnorthernbean = 1 * filedata.greatnorthernbean;
        const kidneybean = 1 * filedata.kidneybean;
        const limabean = 1 * filedata.limabean;
        const pintobean = 1 * filedata.pintobean;
        const favabean = 1 * filedata.favabean;
        const navybean = 1 * filedata.navybean;
        const adzukibean = 1 * filedata.adzukibean;
        const edamame = 1 * filedata.edamame;
        const mungbean = 1 * filedata.mungbean;
        const cranberrybean = 1 * filedata.cranberrybean;
        const thyme = 1 * filedata.thyme;
        const basil = 1 * filedata.basil;
        const oregano = 1 * filedata.oregano;
        const rosemary = 1 * filedata.rosemary;
        const fennelseed = 1 * filedata.fennelseed;
        const bayleaf = 1 * filedata.bayleaf;
        const chilipowder = 1 * filedata.chilipowder;
        const smokedpaprika = 1 * filedata.smokedpaprika;
        const cayenne = 1 * filedata.cayenne;
        const cumin = 1 * filedata.cumin;
        const groundcardamom = 1 * filedata.groundcardamom;
        const currypowder = 1 * filedata.currypowder;
        const onionpowder = 1 * filedata.onionpowder;
        const garlicpowder = 1 * filedata.garlicpowder;
        const groundmustard = 1 * filedata.groundmustard;
        const clove = 1 * filedata.clove;
        const nutmeg = 1 * filedata.nutmeg;
        const cinnamon = 1 * filedata.cinnamon;
        const groundginger = 1 * filedata.groundginger;
        const mace = 1 * filedata.mace;
        const pepper = 1 * filedata.pepper;
        const cow = 1 * filedata.cow;
        const pig = 1 * filedata.pig;
        const horse = 1 * filedata.horse;
        const chicken = 1 * filedata.chicken;
        const sheep = 1 * filedata.sheep;
        const goat = 1 * filedata.goat;
        const llama = 1 * filedata.llama;
        const rabbit = 1 * filedata.rabbit;
        const cement = 1 * filedata.cement;
        const concrete = 1 * filedata.concrete;
        const pebble = 1 * filedata.pebble;
        const phenolicfoam = 1 * filedata.phenolicfoam;
        const polyurethane = 1 * filedata.polyurethane;
        const xps = 1 * filedata.xps;
        const rockwool = 1 * filedata.rockwool;
        const foamglass = 1 * filedata.foamglass;
        const glasswool = 1 * filedata.glasswool;
        const doubleglass = 1 * filedata.doubleglass;
        const tripleglass = 1 * filedata.tripleglass;
        const fabric = 1 * filedata.fabric;
        const cotton = 1 * filedata.cotton;
        const fibre = 1 * filedata.fibre;
        const carbonfibre = 1 * filedata.carbonfibre;
        const chemical = 1 * filedata.chemical;
        const polymaterial = 1 * filedata.polymaterial;
        const acid = 1 * filedata.acid;
        const catalyst = 1 * filedata.catalyst;
        const chromepart = 1 * filedata.chromepart;
        const chrome = 1 * filedata.chrome;
        const brasspart = 1 * filedata.brasspart;
        const brass = 1 * filedata.brass;
        const diamond = 1 * filedata.diamond;
        const gold = 1 * filedata.gold;
        const platinum = 1 * filedata.platinum;
        const silver = 1 * filedata.silver;
        const copper = 1 * filedata.copper;
        const lithium = 1 * filedata.lithium;
        const cobalt = 1 * filedata.cobalt;
        const titanium = 1 * filedata.titanium;
        const tungsten = 1 * filedata.tungsten;
        const nickel = 1 * filedata.nickel;
        const magnesium = 1 * filedata.magnesium;
        const lead = 1 * filedata.lead;
        const tin = 1 * filedata.tin;
        const mercury = 1 * filedata.mercury;
        const bismuth = 1 * filedata.bismuth;
        const rodium = 1 * filedata.rodium;
        const osmium = 1 * filedata.osmium;
        const palladium = 1 * filedata.palladium;
        const iridium = 1 * filedata.iridium;
        const ruthenium = 1 * filedata.ruthenium;
        const plutonium = 1 * filedata.plutonium;
        const componentelectric = 1 * filedata.componentelectric;
        const componentinterior = 1 * filedata.componentinterior;
        const componentclothing = 1 * filedata.componentclothing;
        const componentstarting = 1 * filedata.componentstarting;

        file.set("steel", steel);
        file.set("steelpart", steelpart);
        file.set("iron", iron);
        file.set("carbon", carbon);
        file.set("brick", brick);
        file.set("clay", clay);
        file.set("soil", soil);
        file.set("water", water);
        file.set("woodplank", woodplank);
        file.set("woodpart", woodpart);
        file.set("wood", wood);
        file.set("log", log);
        file.set("bamboo", bamboo);
        file.set("pipe", pipe);
        file.set("plasticpart", plasticpart);
        file.set("plastic", plastic);
        file.set("glass", glass);
        file.set("limestone", limestone);
        file.set("sand", sand);
        file.set("plexiglass", plexiglass);
        file.set("granite", granite);
        file.set("marble", marble);
        file.set("quartz", quartz);
        file.set("chalk", chalk);
        file.set("slate", slate);
        file.set("basalt", basalt);
        file.set("oil", oil);
        file.set("coal", coal);
        file.set("ironore", ironore);
        file.set("copperore", copperore);
        file.set("goldore", goldore);
        file.set("gas", gas);
        file.set("ceramic", ceramic);
        file.set("cork", cork);
        file.set("mesh", mesh);
        file.set("rubber", rubber);
        file.set("uranium", uranium);
        file.set("rice", rice);
        file.set("rye", rye);
        file.set("oats", oats);
        file.set("corn", corn);
        file.set("barley", barley);
        file.set("cassava", cassava);
        file.set("soybean", soybean);
        file.set("sorghum", sorghum);
        file.set("wheat", wheat);
        file.set("resin", resin);
        file.set("tape", tape);
        file.set("glue", glue);
        file.set("paper", paper);
        file.set("steelsheet", steelsheet);
        file.set("cocoabean", cocoabean);
        file.set("coffeebean", coffeebean);
        file.set("sugar", sugar);
        file.set("salt", salt);
        file.set("flower", flower);
        file.set("bakingpowder", bakingpowder);
        file.set("egg", egg);
        file.set("fish", fish);
        file.set("meat", meat);
        file.set("bread", bread);
        file.set("asparagus", asparagus);
        file.set("eggplant", eggplant);
        file.set("broccoli", broccoli);
        file.set("cabbage", cabbage);
        file.set("avocado", avocado);
        file.set("brusselssprout", brusselssprout);
        file.set("carrot", carrot);
        file.set("beetroot", beetroot);
        file.set("garlic", garlic);
        file.set("celery", celery);
        file.set("cucumber", cucumber);
        file.set("greenbean", greenbean);
        file.set("leek", leek);
        file.set("lettuce", lettuce);
        file.set("mushroom", mushroom);
        file.set("onion", onion);
        file.set("pea", pea);
        file.set("pumpkin", pumpkin);
        file.set("radish", radish);
        file.set("rhubarb", rhubarb);
        file.set("sweetpepper", sweetpepper);
        file.set("spinach", spinach);
        file.set("tomato", tomato);
        file.set("sweetpotato", sweetpotato);
        file.set("yam", yam);
        file.set("potato", potato);
        file.set("acerola", acerola);
        file.set("apple", apple);
        file.set("apricot", apricot);
        file.set("banana", banana);
        file.set("blackberry", blackberry);
        file.set("blackcurrant", blackcurrant);
        file.set("blueberry", blueberry);
        file.set("breadfruit", breadfruit);
        file.set("cantaloupe", cantaloupe);
        file.set("cherry", cherry);
        file.set("clementine", clementine);
        file.set("coconut", coconut);
        file.set("cranberry", cranberry);
        file.set("datefruit", datefruit);
        file.set("fig", fig);
        file.set("gooseberry", gooseberry);
        file.set("grapefruit", grapefruit);
        file.set("grape", grape);
        file.set("guava", guava);
        file.set("honeydewmelon", honeydewmelon);
        file.set("jackfruit", jackfruit);
        file.set("jujubefruit", jujubefruit);
        file.set("kiwifruit", kiwifruit);
        file.set("kumquat", kumquat);
        file.set("lemon", lemon);
        file.set("lime", lime);
        file.set("lychee", lychee);
        file.set("mandarin", mandarin);
        file.set("mango", mango);
        file.set("mulberry", mulberry);
        file.set("olive", olive);
        file.set("orange", orange);
        file.set("papaya", papaya);
        file.set("passionfruit", passionfruit);
        file.set("peach", peach);
        file.set("pear", pear);
        file.set("dragonfruit", dragonfruit);
        file.set("pineapple", pineapple);
        file.set("plum", plum);
        file.set("pomegranate", pomegranate);
        file.set("prune", prune);
        file.set("raspberry", raspberry);
        file.set("strawberry", strawberry);
        file.set("tangerine", tangerine);
        file.set("watermelon", watermelon);
        file.set("blackbean", blackbean);
        file.set("blackeyedpea", blackeyedpea);
        file.set("cannellinibean", cannellinibean);
        file.set("chickpea", chickpea);
        file.set("greatnorthernbean", greatnorthernbean);
        file.set("kidneybean", kidneybean);
        file.set("limabean", limabean);
        file.set("pintobean", pintobean);
        file.set("favabean", favabean);
        file.set("navybean", navybean);
        file.set("adzukibean", adzukibean);
        file.set("edamame", edamame);
        file.set("mungbean", mungbean);
        file.set("cranberrybean", cranberrybean);
        file.set("thyme", thyme);
        file.set("basil", basil);
        file.set("oregano", oregano);
        file.set("rosemary", rosemary);
        file.set("fennelseed", fennelseed);
        file.set("bayleaf", bayleaf);
        file.set("chilipowder", chilipowder);
        file.set("smokedpaprika", smokedpaprika);
        file.set("cayenne", cayenne);
        file.set("cumin", cumin);
        file.set("groundcardamom", groundcardamom);
        file.set("currypowder", currypowder);
        file.set("onionpowder", onionpowder);
        file.set("garlicpowder", garlicpowder);
        file.set("groundmustard", groundmustard);
        file.set("clove", clove);
        file.set("nutmeg", nutmeg);
        file.set("cinnamon", cinnamon);
        file.set("groundginger", groundginger);
        file.set("mace", mace);
        file.set("pepper", pepper)
        file.set("cow", cow);
        file.set("pig", pig);
        file.set("horse", horse);
        file.set("chicken", chicken);
        file.set("sheep", sheep);
        file.set("goat", goat);
        file.set("llama", llama);
        file.set("rabbit", rabbit);
        file.set("cement", cement);
        file.set("concrete", concrete);
        file.set("pebble", pebble);
        file.set("phenolicfoam", phenolicfoam);
        file.set("polyurethane", polyurethane);
        file.set("xps", xps);
        file.set("rockwool", rockwool);
        file.set("foamglass", foamglass);
        file.set("glasswool", glasswool);
        file.set("doubleglass", doubleglass);
        file.set("tripleglass", tripleglass);
        file.set("fabric", fabric);
        file.set("cotton", cotton);
        file.set("fibre", fibre);
        file.set("carbonfibre", carbonfibre);
        file.set("chemical", chemical);
        file.set("polymaterial", polymaterial);
        file.set("acid", acid);
        file.set("catalyst", catalyst);
        file.set("chromepart", chromepart);
        file.set("chrome", chrome);
        file.set("brasspart", brasspart);
        file.set("brass", brass);
        file.set("diamond", diamond);
        file.set("gold", gold);
        file.set("platinum", platinum);
        file.set("silver", silver);
        file.set("copper", copper);
        file.set("lithium", lithium);
        file.set("cobalt", cobalt);
        file.set("titanium", titanium);
        file.set("tungsten", tungsten);
        file.set("nickel", nickel);
        file.set("magnesium", magnesium);
        file.set("lead", lead);
        file.set("tin", tin);
        file.set("mercury", mercury);
        file.set("bismuth", bismuth);
        file.set("rodium", rodium);
        file.set("osmium", osmium);
        file.set("palladium", palladium);
        file.set("iridium", iridium);
        file.set("ruthenium", ruthenium);
        file.set("plutonium", plutonium);
        file.set("componentelectric", componentelectric);
        file.set("componentinterior", componentinterior);
        file.set("componentclothing", componentclothing);
        file.set("componentstarting", componentstarting);
        file.save();
    },
};