// Draai de richtingscoefficienten uit.

const config = require("../Other/config.js");
const profileModel = require("../models/profileSchema");
const editJsonFile = require("edit-json-file");

module.exports = {
    name: "cross",
    aliases: config.aliases.aliasescross,
    cooldown: config.cooldown.cooldowncross,
    permissions: config.permissions.permissioncross,
    description: "Bulk write slope data.",
    async execute(message, args, cmd, client, Discord, profileData) {
        message.channel.send(`Received, check console.`);
        let file = editJsonFile(`./formula-b.json`) // target file
        const filedata1 = require('./../formula-a.json') // y
        const filedata2 = require('./../marketpricemin.json') // x

        const steel = (filedata2.steel - ( 15000 * filedata1.steel))
        const steelpart = (filedata2.steelpart - ( 15000 * filedata1.steelpart))
        const iron = (filedata2.iron - ( 15000 * filedata1.iron))
        const carbon = (filedata2.carbon - ( 15000 * filedata1.carbon))
        const brick = (filedata2.brick - ( 15000 * filedata1.brick))
        const clay = (filedata2.clay - ( 15000 * filedata1.clay))
        const soil = (filedata2.soil - ( 15000 * filedata1.soil))
        const water = (filedata2.water - ( 15000 * filedata1.water))
        const woodplank = (filedata2.woodplank - ( 15000 * filedata1.woodplank))
        const woodpart = (filedata2.woodpart - ( 15000 * filedata1.woodpart))
        const wood = (filedata2.wood - ( 15000 * filedata1.wood))
        const log = (filedata2.log - ( 15000 * filedata1.log))
        const bamboo = (filedata2.bamboo - ( 15000 * filedata1.bamboo))
        const pipe = (filedata2.pipe - ( 15000 * filedata1.pipe))
        const plasticpart = (filedata2.plasticpart - ( 15000 * filedata1.plasticpart))
        const plastic = (filedata2.plastic - ( 15000 * filedata1.plastic))
        const glass = (filedata2.glass - ( 15000 * filedata1.glass))
        const limestone = (filedata2.limestone - ( 15000 * filedata1.limestone))
        const sand = (filedata2.sand - ( 15000 * filedata1.sand))
        const plexiglass = (filedata2.plexiglass - ( 15000 * filedata1.plexiglass))
        const granite = (filedata2.granite - ( 15000 * filedata1.granite))
        const marble = (filedata2.marble - ( 15000 * filedata1.marble))
        const quartz = (filedata2.quartz - ( 15000 * filedata1.quartz))
        const chalk = (filedata2.chalk - ( 15000 * filedata1.chalk))
        const slate = (filedata2.slate - ( 15000 * filedata1.slate))
        const basalt = (filedata2.basalt - ( 15000 * filedata1.basalt))
        const oil = (filedata2.oil - ( 15000 * filedata1.oil))
        const coal = (filedata2.coal - ( 15000 * filedata1.coal))
        const ironore = (filedata2.ironore - ( 15000 * filedata1.ironore))
        const copperore = (filedata2.copperore - ( 15000 * filedata1.copperore))
        const goldore = (filedata2.goldore - ( 15000 * filedata1.goldore))
        const gas = (filedata2.gas - ( 15000 * filedata1.gas))
        const ceramic = (filedata2.ceramic - ( 15000 * filedata1.ceramic))
        const cork = (filedata2.cork - ( 15000 * filedata1.cork))
        const mesh = (filedata2.mesh - ( 15000 * filedata1.mesh))
        const rubber = (filedata2.rubber - ( 15000 * filedata1.rubber))
        const uranium = (filedata2.uranium - ( 15000 * filedata1.uranium))
        const rice = (filedata2.rice - ( 15000 * filedata1.rice))
        const rye = (filedata2.rye - ( 15000 * filedata1.rye))
        const oats = (filedata2.oats - ( 15000 * filedata1.oats))
        const corn = (filedata2.corn - ( 15000 * filedata1.corn))
        const barley = (filedata2.barley - ( 15000 * filedata1.barley))
        const cassava = (filedata2.cassava - ( 15000 * filedata1.cassava))
        const soybean = (filedata2.soybean - ( 15000 * filedata1.soybean))
        const sorghum = (filedata2.sorghum - ( 15000 * filedata1.sorghum))
        const wheat = (filedata2.wheat - ( 15000 * filedata1.wheat))
        const resin = (filedata2.resin - ( 15000 * filedata1.resin))
        const tape = (filedata2.tape - ( 15000 * filedata1.tape))
        const steelsheet = (filedata2.steelsheet - ( 15000 * filedata1.steelsheet))
        const cocoabean = (filedata2.cocoabean - ( 15000 * filedata1.cocoabean))
        const coffeebean = (filedata2.coffeebean - ( 15000 * filedata1.coffeebean))
        const sugar = (filedata2.sugar - ( 15000 * filedata1.sugar))
        const salt = (filedata2.salt - ( 15000 * filedata1.salt))
        const flower = (filedata2.flower - ( 15000 * filedata1.flower))
        const bakingpowder = (filedata2.bakingpowder - ( 15000 * filedata1.bakingpowder))
        const egg = (filedata2.egg - ( 15000 * filedata1.egg))
        const fish = (filedata2.fish - ( 15000 * filedata1.fish))
        const meat = (filedata2.meat - ( 15000 * filedata1.meat))
        const bread = (filedata2.bread - ( 15000 * filedata1.bread))
        const asparagus = (filedata2.asparagus - ( 15000 * filedata1.asparagus))
        const eggplant = (filedata2.eggplant - ( 15000 * filedata1.eggplant))
        const broccoli = (filedata2.broccoli - ( 15000 * filedata1.broccoli))
        const cabbage = (filedata2.cabbage - ( 15000 * filedata1.cabbage))
        const avocado = (filedata2.avocado - ( 15000 * filedata1.avocado))
        const brusselssprout = (filedata2.brusselssprout - ( 15000 * filedata1.brusselssprout))
        const carrot = (filedata2.carrot - ( 15000 * filedata1.carrot))
        const beetroot = (filedata2.beetroot - ( 15000 * filedata1.beetroot))
        const garlic = (filedata2.garlic - ( 15000 * filedata1.garlic))
        const celery = (filedata2.celery - ( 15000 * filedata1.celery))
        const cucumber = (filedata2.cucumber - ( 15000 * filedata1.cucumber))
        const greenbean = (filedata2.greenbean - ( 15000 * filedata1.greenbean))
        const leek = (filedata2.leek - ( 15000 * filedata1.leek))
        const lettuce = (filedata2.lettuce - ( 15000 * filedata1.lettuce))
        const mushroom = (filedata2.mushroom - ( 15000 * filedata1.mushroom))
        const onion = (filedata2.onion - ( 15000 * filedata1.onion))
        const pea = (filedata2.pea - ( 15000 * filedata1.pea))
        const pumpkin = (filedata2.pumpkin - ( 15000 * filedata1.pumpkin))
        const radish = (filedata2.radish - ( 15000 * filedata1.radish))
        const rhubarb = (filedata2.rhubarb - ( 15000 * filedata1.rhubarb))
        const sweetpepper = (filedata2.sweetpepper - ( 15000 * filedata1.sweetpepper))
        const spinach = (filedata2.spinach - ( 15000 * filedata1.spinach))
        const tomato = (filedata2.tomato - ( 15000 * filedata1.tomato))
        const sweetpotato = (filedata2.sweetpotato - ( 15000 * filedata1.sweetpotato))
        const yam = (filedata2.yam - ( 15000 * filedata1.yam))
        const potato = (filedata2.potato - ( 15000 * filedata1.potato))
        const acerola = (filedata2.acerola - ( 15000 * filedata1.acerola))
        const apple = (filedata2.apple - ( 15000 * filedata1.apple))
        const apricot = (filedata2.apricot - ( 15000 * filedata1.apricot))
        const banana = (filedata2.banana - ( 15000 * filedata1.banana))
        const blackberry = (filedata2.blackberry - ( 15000 * filedata1.blackberry))
        const blackcurrant = (filedata2.blackcurrant - ( 15000 * filedata1.blackcurrant))
        const blueberry = (filedata2.blueberry - ( 15000 * filedata1.blueberry))
        const breadfruit = (filedata2.breadfruit - ( 15000 * filedata1.breadfruit))
        const cantaloupe = (filedata2.cantaloupe - ( 15000 * filedata1.cantaloupe))
        const cherry = (filedata2.cherry - ( 15000 * filedata1.cherry))
        const clementine = (filedata2.clementine - ( 15000 * filedata1.clementine))
        const coconut = (filedata2.coconut - ( 15000 * filedata1.coconut))
        const cranberry = (filedata2.cranberry - ( 15000 * filedata1.cranberry))
        const datefruit = (filedata2.datefruit - ( 15000 * filedata1.datefruit))
        const fig = (filedata2.fig - ( 15000 * filedata1.fig))
        const gooseberry = (filedata2.gooseberry - ( 15000 * filedata1.gooseberry))
        const grapefruit = (filedata2.grapefruit - ( 15000 * filedata1.grapefruit))
        const grape = (filedata2.grape - ( 15000 * filedata1.grape))
        const guava = (filedata2.guava - ( 15000 * filedata1.guava))
        const honeydewmelon = (filedata2.honeydewmelon - ( 15000 * filedata1.honeydewmelon))
        const jackfruit = (filedata2.jackfruit - ( 15000 * filedata1.jackfruit))
        const jujubefruit = (filedata2.jujubefruit - ( 15000 * filedata1.jujubefruit))
        const kiwifruit = (filedata2.kiwifruit - ( 15000 * filedata1.kiwifruit))
        const kumquat = (filedata2.kumquat - ( 15000 * filedata1.kumquat))
        const lemon = (filedata2.lemon - ( 15000 * filedata1.lemon))
        const lime = (filedata2.lime - ( 15000 * filedata1.lime))
        const lychee = (filedata2.lychee - ( 15000 * filedata1.lychee))
        const mandarin = (filedata2.mandarin - ( 15000 * filedata1.mandarin))
        const mango = (filedata2.mango - ( 15000 * filedata1.mango))
        const mulberry = (filedata2.mulberry - ( 15000 * filedata1.mulberry))
        const olive = (filedata2.olive - ( 15000 * filedata1.olive))
        const orange = (filedata2.orange - ( 15000 * filedata1.orange))
        const papaya = (filedata2.papaya - ( 15000 * filedata1.papaya))
        const passionfruit = (filedata2.passionfruit - ( 15000 * filedata1.passionfruit))
        const peach = (filedata2.peach - ( 15000 * filedata1.peach))
        const pear = (filedata2.pear - ( 15000 * filedata1.pear))
        const dragonfruit = (filedata2.dragonfruit - ( 15000 * filedata1.dragonfruit))
        const pineapple = (filedata2.pineapple - ( 15000 * filedata1.pineapple))
        const plum = (filedata2.plum - ( 15000 * filedata1.plum))
        const pomegranate = (filedata2.pomegranate - ( 15000 * filedata1.pomegranate))
        const prune = (filedata2.prune - ( 15000 * filedata1.prune))
        const raspberry = (filedata2.raspberry - ( 15000 * filedata1.raspberry))
        const strawberry = (filedata2.strawberry - ( 15000 * filedata1.strawberry))
        const tangerine = (filedata2.tangerine - ( 15000 * filedata1.tangerine))
        const watermelon = (filedata2.watermelon - ( 15000 * filedata1.watermelon))
        const blackbean = (filedata2.blackbean - ( 15000 * filedata1.blackbean))
        const blackeyedpea = (filedata2.blackeyedpea - ( 15000 * filedata1.blackeyedpea))
        const cannellinibean = (filedata2.cannellinibean - ( 15000 * filedata1.cannellinibean))
        const chickpea = (filedata2.chickpea - ( 15000 * filedata1.chickpea))
        const greatnorthernbean = (filedata2.greatnorthernbean - ( 15000 * filedata1.greatnorthernbean))
        const kidneybean = (filedata2.kidneybean - ( 15000 * filedata1.kidneybean))
        const limabean = (filedata2.limabean - ( 15000 * filedata1.limabean))
        const pintobean = (filedata2.pintobean - ( 15000 * filedata1.pintobean))
        const favabean = (filedata2.favabean - ( 15000 * filedata1.favabean))
        const navybean = (filedata2.navybean - ( 15000 * filedata1.navybean))
        const adzukibean = (filedata2.adzukibean - ( 15000 * filedata1.adzukibean))
        const edamame = (filedata2.edamame - ( 15000 * filedata1.edamame))
        const mungbean = (filedata2.mungbean - ( 15000 * filedata1.mungbean))
        const cranberrybean = (filedata2.cranberrybean - ( 15000 * filedata1.cranberrybean))
        const thyme = (filedata2.thyme - ( 15000 * filedata1.thyme))
        const basil = (filedata2.basil - ( 15000 * filedata1.basil))
        const oregano = (filedata2.oregano - ( 15000 * filedata1.oregano))
        const rosemary = (filedata2.rosemary - ( 15000 * filedata1.rosemary))
        const fennelseed = (filedata2.fennelseed - ( 15000 * filedata1.fennelseed))
        const bayleaf = (filedata2.bayleaf - ( 15000 * filedata1.bayleaf))
        const chilipowder = (filedata2.chilipowder - ( 15000 * filedata1.chilipowder))
        const smokedpaprika = (filedata2.smokedpaprika - ( 15000 * filedata1.smokedpaprika))
        const cayenne = (filedata2.cayenne - ( 15000 * filedata1.cayenne))
        const cumin = (filedata2.cumin - ( 15000 * filedata1.cumin))
        const groundcardamom = (filedata2.groundcardamom - ( 15000 * filedata1.groundcardamom))
        const currypowder = (filedata2.currypowder - ( 15000 * filedata1.currypowder))
        const onionpowder = (filedata2.onionpowder - ( 15000 * filedata1.onionpowder))
        const garlicpowder = (filedata2.garlicpowder - ( 15000 * filedata1.garlicpowder))
        const groundmustard = (filedata2.groundmustard - ( 15000 * filedata1.groundmustard))
        const clove = (filedata2.clove - ( 15000 * filedata1.clove))
        const nutmeg = (filedata2.nutmeg - ( 15000 * filedata1.nutmeg))
        const cinnamon = (filedata2.cinnamon - ( 15000 * filedata1.cinnamon))
        const groundginger = (filedata2.groundginger - ( 15000 * filedata1.groundginger))
        const mace = (filedata2.mace - ( 15000 * filedata1.mace))
        const cow = (filedata2.cow - ( 15000 * filedata1.cow))
        const pig = (filedata2.pig - ( 15000 * filedata1.pig))
        const horse = (filedata2.horse - ( 15000 * filedata1.horse))
        const chicken = (filedata2.chicken - ( 15000 * filedata1.chicken))
        const sheep = (filedata2.sheep - ( 15000 * filedata1.sheep))
        const goat = (filedata2.goat - ( 15000 * filedata1.goat))
        const llama = (filedata2.llama - ( 15000 * filedata1.llama))
        const rabbit = (filedata2.rabbit - ( 15000 * filedata1.rabbit))
        const cement = (filedata2.cement - ( 15000 * filedata1.cement))
        const concrete = (filedata2.concrete - ( 15000 * filedata1.concrete))
        const pebble = (filedata2.pebble - ( 15000 * filedata1.pebble))
        const phenolicfoam = (filedata2.phenolicfoam - ( 15000 * filedata1.phenolicfoam))
        const polyurethane = (filedata2.polyurethane - ( 15000 * filedata1.polyurethane))
        const xps = (filedata2.xps - ( 15000 * filedata1.xps))
        const rockwool = (filedata2.rockwool - ( 15000 * filedata1.rockwool))
        const foamglass = (filedata2.foamglass - ( 15000 * filedata1.foamglass))
        const glasswool = (filedata2.glasswool - ( 15000 * filedata1.glasswool))
        const doubleglass = (filedata2.doubleglass - ( 15000 * filedata1.doubleglass))
        const tripleglass = (filedata2.tripleglass - ( 15000 * filedata1.tripleglass))
        const fabric = (filedata2.fabric - ( 15000 * filedata1.fabric))
        const cotton = (filedata2.cotton - ( 15000 * filedata1.cotton))
        const fibre = (filedata2.fibre - ( 15000 * filedata1.fibre))
        const carbonfibre = (filedata2.carbonfibre - ( 15000 * filedata1.carbonfibre))
        const chemical = (filedata2.chemical - ( 15000 * filedata1.chemical))
        const polymaterial = (filedata2.polymaterial - ( 15000 * filedata1.polymaterial))
        const acid = (filedata2.acid - ( 15000 * filedata1.acid))
        const catalyst = (filedata2.catalyst - ( 15000 * filedata1.catalyst))
        const chromepart = (filedata2.chromepart - ( 15000 * filedata1.chromepart))
        const chrome = (filedata2.chrome - ( 15000 * filedata1.chrome))
        const brasspart = (filedata2.brasspart - ( 15000 * filedata1.brasspart))
        const brass = (filedata2.brass - ( 15000 * filedata1.brass))
        const diamond = (filedata2.diamond - ( 15000 * filedata1.diamond))
        const gold = (filedata2.gold - ( 15000 * filedata1.gold))
        const platinum = (filedata2.platinum - ( 15000 * filedata1.platinum))
        const silver = (filedata2.silver - ( 15000 * filedata1.silver))
        const copper = (filedata2.copper - ( 15000 * filedata1.copper))
        const lithium = (filedata2.lithium - ( 15000 * filedata1.lithium))
        const cobalt = (filedata2.cobalt - ( 15000 * filedata1.cobalt))
        const titanium = (filedata2.titanium - ( 15000 * filedata1.titanium))
        const tungsten = (filedata2.tungsten - ( 15000 * filedata1.tungsten))
        const nickel = (filedata2.nickel - ( 15000 * filedata1.nickel))
        const magnesium = (filedata2.magnesium - ( 15000 * filedata1.magnesium))
        const lead = (filedata2.lead - ( 15000 * filedata1.lead))
        const tin = (filedata2.tin - ( 15000 * filedata1.tin))
        const mercury = (filedata2.mercury - ( 15000 * filedata1.mercury))
        const bismuth = (filedata2.bismuth - ( 15000 * filedata1.bismuth))
        const rodium = (filedata2.rodium - ( 15000 * filedata1.rodium))
        const osmium = (filedata2.osmium - ( 15000 * filedata1.osmium))
        const palladium = (filedata2.palladium - ( 15000 * filedata1.palladium))
        const iridium = (filedata2.iridium - ( 15000 * filedata1.iridium))
        const ruthenium = (filedata2.ruthenium - ( 15000 * filedata1.ruthenium))
        const plutonium = (filedata2.plutonium - ( 15000 * filedata1.plutonium))
        const componentelectric = (filedata2.componentelectric - ( 15000 * filedata1.componentelectric))
        const componentinterior = (filedata2.componentinterior - ( 15000 * filedata1.componentinterior))
        const componentclothing = (filedata2.componentclothing - ( 15000 * filedata1.componentclothing))
        const componentstarting = (filedata2.componentstarting - ( 15000 * filedata1.componentstarting))

        file.set("steel", steel)
        file.set("steelpart", steelpart)
        file.set("iron", iron)
        file.set("carbon", carbon)
        file.set("brick", brick)
        file.set("clay", clay)
        file.set("soil", soil)
        file.set("water", water)
        file.set("woodplank", woodplank)
        file.set("woodpart", woodpart)
        file.set("wood", wood)
        file.set("log", log)
        file.set("bamboo", bamboo)
        file.set("pipe", pipe)
        file.set("plasticpart", plasticpart)
        file.set("plastic", plastic)
        file.set("glass", glass)
        file.set("limestone", limestone)
        file.set("sand", sand)
        file.set("plexiglass", plexiglass)
        file.set("granite", granite)
        file.set("marble", marble)
        file.set("quartz", quartz)
        file.set("chalk", chalk)
        file.set("slate", slate)
        file.set("basalt", basalt)
        file.set("oil", oil)
        file.set("coal", coal)
        file.set("ironore", ironore)
        file.set("copperore", copperore)
        file.set("goldore", goldore)
        file.set("gas", gas)
        file.set("ceramic", ceramic)
        file.set("cork", cork)
        file.set("mesh", mesh)
        file.set("rubber", rubber)
        file.set("uranium", uranium)
        file.set("rice", rice)
        file.set("rye", rye)
        file.set("oats", oats)
        file.set("corn", corn)
        file.set("barley", barley)
        file.set("cassava", cassava)
        file.set("soybean", soybean)
        file.set("sorghum", sorghum)
        file.set("wheat", wheat)
        file.set("resin", resin)
        file.set("tape", tape)
        file.set("steelsheet", steelsheet)
        file.set("cocoabean", cocoabean)
        file.set("coffeebean", coffeebean)
        file.set("sugar", sugar)
        file.set("salt", salt)
        file.set("flower", flower)
        file.set("bakingpowder", bakingpowder)
        file.set("egg", egg)
        file.set("fish", fish)
        file.set("meat", meat)
        file.set("bread", bread)
        file.set("asparagus", asparagus)
        file.set("eggplant", eggplant)
        file.set("broccoli", broccoli)
        file.set("cabbage", cabbage)
        file.set("avocado", avocado)
        file.set("brusselssprout", brusselssprout)
        file.set("carrot", carrot)
        file.set("beetroot", beetroot)
        file.set("garlic", garlic)
        file.set("celery", celery)
        file.set("cucumber", cucumber)
        file.set("greenbean", greenbean)
        file.set("leek", leek)
        file.set("lettuce", lettuce)
        file.set("mushroom", mushroom)
        file.set("onion", onion)
        file.set("pea", pea)
        file.set("pumpkin", pumpkin)
        file.set("radish", radish)
        file.set("rhubarb", rhubarb)
        file.set("sweetpepper", sweetpepper)
        file.set("spinach", spinach)
        file.set("tomato", tomato)
        file.set("sweetpotato", sweetpotato)
        file.set("yam", yam)
        file.set("potato", potato)
        file.set("acerola", acerola)
        file.set("apple", apple)
        file.set("apricot", apricot)
        file.set("banana", banana)
        file.set("blackberry", blackberry)
        file.set("blackcurrant", blackcurrant)
        file.set("blueberry", blueberry)
        file.set("breadfruit", breadfruit)
        file.set("cantaloupe", cantaloupe)
        file.set("cherry", cherry)
        file.set("clementine", clementine)
        file.set("coconut", coconut)
        file.set("cranberry", cranberry)
        file.set("datefruit", datefruit)
        file.set("fig", fig)
        file.set("gooseberry", gooseberry)
        file.set("grapefruit", grapefruit)
        file.set("grape", grape)
        file.set("guava", guava)
        file.set("honeydewmelon", honeydewmelon)
        file.set("jackfruit", jackfruit)
        file.set("jujubefruit", jujubefruit)
        file.set("kiwifruit", kiwifruit)
        file.set("kumquat", kumquat)
        file.set("lemon", lemon)
        file.set("lime", lime)
        file.set("lychee", lychee)
        file.set("mandarin", mandarin)
        file.set("mango", mango)
        file.set("mulberry", mulberry)
        file.set("olive", olive)
        file.set("orange", orange)
        file.set("papaya", papaya)
        file.set("passionfruit", passionfruit)
        file.set("peach", peach)
        file.set("pear", pear)
        file.set("dragonfruit", dragonfruit)
        file.set("pineapple", pineapple)
        file.set("plum", plum)
        file.set("pomegranate", pomegranate)
        file.set("prune", prune)
        file.set("raspberry", raspberry)
        file.set("strawberry", strawberry)
        file.set("tangerine", tangerine)
        file.set("watermelon", watermelon)
        file.set("blackbean", blackbean)
        file.set("blackeyedpea", blackeyedpea)
        file.set("cannellinibean", cannellinibean)
        file.set("chickpea", chickpea)
        file.set("greatnorthernbean", greatnorthernbean)
        file.set("kidneybean", kidneybean)
        file.set("limabean", limabean)
        file.set("pintobean", pintobean)
        file.set("favabean", favabean)
        file.set("navybean", navybean)
        file.set("adzukibean", adzukibean)
        file.set("edamame", edamame)
        file.set("mungbean", mungbean)
        file.set("cranberrybean", cranberrybean)
        file.set("thyme", thyme)
        file.set("basil", basil)
        file.set("oregano", oregano)
        file.set("rosemary", rosemary)
        file.set("fennelseed", fennelseed)
        file.set("bayleaf", bayleaf)
        file.set("chilipowder", chilipowder)
        file.set("smokedpaprika", smokedpaprika)
        file.set("cayenne", cayenne)
        file.set("cumin", cumin)
        file.set("groundcardamom", groundcardamom)
        file.set("currypowder", currypowder)
        file.set("onionpowder", onionpowder)
        file.set("garlicpowder", garlicpowder)
        file.set("groundmustard", groundmustard)
        file.set("clove", clove)
        file.set("nutmeg", nutmeg)
        file.set("cinnamon", cinnamon)
        file.set("groundginger", groundginger)
        file.set("mace", mace)
        file.set("cow", cow)
        file.set("pig", pig)
        file.set("horse", horse)
        file.set("chicken", chicken)
        file.set("sheep", sheep)
        file.set("goat", goat)
        file.set("llama", llama)
        file.set("rabbit", rabbit)
        file.set("cement", cement)
        file.set("concrete", concrete)
        file.set("pebble", pebble)
        file.set("phenolicfoam", phenolicfoam)
        file.set("polyurethane", polyurethane)
        file.set("xps", xps)
        file.set("rockwool", rockwool)
        file.set("foamglass", foamglass)
        file.set("glasswool", glasswool)
        file.set("doubleglass", doubleglass)
        file.set("tripleglass", tripleglass)
        file.set("fabric", fabric)
        file.set("cotton", cotton)
        file.set("fibre", fibre)
        file.set("carbonfibre", carbonfibre)
        file.set("chemical", chemical)
        file.set("polymaterial", polymaterial)
        file.set("acid", acid)
        file.set("catalyst", catalyst)
        file.set("chromepart", chromepart)
        file.set("chrome", chrome)
        file.set("brasspart", brasspart)
        file.set("brass", brass)
        file.set("diamond", diamond)
        file.set("gold", gold)
        file.set("platinum", platinum)
        file.set("silver", silver)
        file.set("copper", copper)
        file.set("lithium", lithium)
        file.set("cobalt", cobalt)
        file.set("titanium", titanium)
        file.set("tungsten", tungsten)
        file.set("nickel", nickel)
        file.set("magnesium", magnesium)
        file.set("lead", lead)
        file.set("tin", tin)
        file.set("mercury", mercury)
        file.set("bismuth", bismuth)
        file.set("rodium", rodium)
        file.set("osmium", osmium)
        file.set("palladium", palladium)
        file.set("iridium", iridium)
        file.set("ruthenium", ruthenium)
        file.set("plutonium", plutonium)
        file.set("componentelectric", componentelectric)
        file.set("componentinterior", componentinterior)
        file.set("componentclothing", componentclothing)
        file.set("componentstarting", componentstarting)
        file.save()
    },
};
